name: Publish CV PDF en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Generar el PDF (demo)
        run: |
          mkdir -p docs
          echo "Contenido del PDF generado automáticamente" > docs/RafaelCV.pdf

      - name: Commit y push del PDF
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/RafaelCV.pdf
          git commit -m "Add Pdf" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/DeveloperRafael1996/cv.git HEAD:main
